### ISSUE TITLE
handle scoped packages

### ISSUE THREAD

**Issue by benoitc** [hexpm/hex#101]
Some projects may use forks or 2 apps/libs could have the same names or sometimes you just want to group packages. IMHO It would would be useful to have a "scoped packages" feature like in NPM: https://docs.npmjs.com/misc/scope

**Comment by josevalim** [comment]
We (the hex team) have talked about this in the past. I don't think this to be necessary, honestly, as the package name does not imply the package name. For example, in mix:

    {:my_fork_hachkey, "0.1.0", app: :hackney}

i.e. Hex already was designed in a way that the package name is not necessarily the app name, it is just a nice convenience when they match.

**Comment by benoitc** [comment]
@josevalim but what if I want to provides plugin, or keep a scope for it? (either by claiming it or registering it first)

**Comment by ericmj** [comment]
@benoitc In that case you can chose a specific naming scheme for the plugs, for example: myapp_plugin1.

We don't want to make it too easy to publish forks because it's bad for the ecosystem if everyone publishes their own fork with some small changes from a project. It's much better if everyone focuses their efforts on the main project.

**Comment by benoitc** [comment]
@ericmj this is more in term of metadata. For example if I am creating a project that accept some plugins using hex.pm to ship it and use the dependencies in. How would I make sure that no one is reusing `myapp_` ?

**Comment by ericmj** [comment]
That could happen with npm scopes also, as far as i can tell from the npm docs there is no way to reserve a scope.

**Comment by benoitc** [comment]
Sorry failed to answer. But on "don't want to make it too easy to publish forks because it's bad for the ecosystem" this is how competition exists though. There are plenty reason to fork and this one of the strength of opensource. 

Anyway it stop somehow to use hex as a distribution platform for companies. Scoping packages also allows someone to group and look for it in an UI. How could that be done using the current version of Hex?

**Comment by ericmj** [comment]
> Sorry failed to answer. But on "don't want to make it too easy to publish forks because it's bad for the ecosystem" this is how competition exists though. There are plenty reason to fork and this one of the strength of opensource.

The first step should be to contribute to the original project. One of the biggest problems with the erlang ecosystem has been that everyone has forked for their little change and hasn't contributed it back to the original project. If you need to fork because the project is dead or the original maintainer is unresponsive you can either take it over on hex.pm (we have a process for this) or you can chose a new name for it.

> Anyway it stop somehow to use hex as a distribution platform for companies.

Can you elaborate?

> Scoping packages also allows someone to group and look for it in an UI. How could that be done using the current version of Hex?

By prefixing. `phoenix` related packages start with `phoenix_`, see for example `phoenix_html` and `phoenix_live_reload`. Same goes for `plug` and many other packages.

**Comment by thiagomajesk** [comment]
This is an old issue, but I think @benoitc is right here, we should probably have scopes. See the approach [JSR](https://jsr.io/docs/scopes) is taking to solve the issues with NPM.

> By prefixing. phoenix related packages start with phoenix_, see for example phoenix_html and phoenix_live_reload. Same goes for plug and many other packages.

Using just prefixes can be confusing and does not guarantee that package comes from the same (trusted) source, for instance, the phoenix team could own the scope `@phoenix` and publish `@phoenix/html`, `@phoenix/live_reload` and `@phoenix/live_view` and users can be sure this comes from the same trusted place (also it avoids package pollution).

**Comment by ericmj** [comment]
`@phoenix/html` is a good example why this is a bad idea for OTP applications. Since application names have to be unique in a project we would greatly increase the risk of collisions. I think there's a good chance of multiple people wanting to use a package named `html`.

**Comment by thiagomajesk** [comment]
Hey @ericmj! Based on Jose's comment I was under the impression that the package name does not need to map to the application name, so I assumed it was just a matter of restricting who can push to specific "scopes" (call it prefixes, namespaces, or organizations if you want). So in this case, it's not just "html" but "@phoenix/html".

**Comment by ericmj** [comment]
That kind of naming is not a standard pattern for OTP app names and having slashes in them would break a bunch of things. It would also mean major breaking changes for anyone that opts into this scoping for existing packages.

**Comment by thiagomajesk** [comment]
Yeah, don't get caught up on the specifics, I just gave an example based on the NPM and JSR package name convention. If this is somehow possible in Elixirland (using whatever mechanism we have available) I think it's worth exploring. I just wanted to echo the OP's request, since we have been learning from other communities in the past 10 years (see the JSR talk for instance).

**Comment by ericmj** [comment]
I am not against scoped packages on principle but to be able to discuss it we need a fleshed out proposal that considers the specific constraints of our ecosystem.
