### ISSUE TITLE
Bug on dependency resolution for package published on 2/29

### ISSUE THREAD

**Issue by chrismccord** [hexpm/hex#1018]
`phoenix_html` 4.1.0 was published yesterday and users (including myself) are unable to resolve deps with `{:phoenix_html, "~> 4.1"}`:

```
Because your app depends on phoenix_html ~> 4.1 which doesn't match any versions, version solving failed.
** (Mix) Hex dependency resolution failed
```

Publishing the same package again today as 4.1.1 fixed this issue, but I am not sure what happened.

**Comment by ericmj** [comment]
I am guessing this was some kind of CDN issue, perhaps with cache purging. These are generally hard to investigate since geographic location will give you different results. I didn't see any logged errors around this time that would be related to this.

Hopefully this was a one off issue, but will monitor to see if it happens again. Thanks for the report Chris!
