### ISSUE TITLE
Private Repos - github authentication

### ISSUE THREAD

**Issue by erneestoc** [hexpm/hex#153]
I'm currently using private github repos for my internal projects. It works great when you have added the key to your ssh agent. But I have a specific machine in where I've the repo, but I don't want to enter an ssh key. 

When I run `mix deps.get`, it prompts for my username `Username for 'https://github.com': `.. And gets stuck there, without asking for a password...

**Comment by josevalim** [comment]
Because we only shell out to git, you do need to have your git properly configured if the proper ssh keys. There isn't much we can do. alternatively you can include username:password in the repo: http://stackoverflow.com/questions/10054318/how-to-provide-username-and-password-when-run-git-clone-gitremote-git
