### ISSUE TITLE
mix local.hex installs hex through http

### ISSUE THREAD

**Issue by pinya** [hexpm/hex#200]
`mix local.hex`  tries to download hex over HTTP, although HTTPS should be much more secure option:
`Are you sure you want to install archive "http://s3.amazonaws.com/s3.hex.pm/installs/1.2.0/hex-0.10.4.ez"? [Yn]`

System is  MacOS X 10.11
Elixir installed from homebrew
```
elixir: stable 1.2.2 (bottled), HEAD
Functional metaprogramming aware language built on Erlang VM
http://elixir-lang.org/
/usr/local/Cellar/elixir/1.2.2 (356 files, 4.4M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/elixir.rb
```

**Comment by josevalim** [comment]
All packages are signed and verified on the Elixir side. We had to add our own public key mechanism because https certificate chains are notariously hard to work in Erlang default's http client (3rd party clients solve the problem well but we cannot depend on them).

@ericmj should we still use the https URL just to avoid confusion?

**Comment by ericmj** [comment]
We could use https but it would only be a false sense of security since certificates are not verified.
