### ISSUE TITLE
`mix local.hex` improve message when replacing existing archive

### ISSUE THREAD

**Issue by eksperimental** [hexpm/hex#222]
```sh
$ mix local.hex
Found existing archive(s): hex-0.11.3.ez.
Are you sure you want to replace them? [Yn]
```

only after I hit <kbd>Y</kbd>, I know what I'm gonna replace that archive with

```sh
* creating ~/.mix/archives/hex-0.11.5.ez
```

I think a message like this will help:
`Are you sure you want to replace them with hex-0.11.5.ez? [Yn]`

**Comment by josevalim** [comment]
Let's please open this on elixir-Lang because the task is defined there. :)
and yes, we should change it. So a PR is welcome!

On Friday, April 8, 2016, eksperimental <notifications@github.com> wrote:

> $ mix local.hex
> Found existing archive(s): hex-0.11.3.ez.
> Are you sure you want to replace them? [Yn]
>
> only after I hit Y, I know what I'm gonna replace that archive with
>
> * creating ~/.mix/archives/hex-0.11.5.ez
>
> I think a message like this will help:
> Are you sure you want to replace them with hex-0.11.5.ez? [Yn]
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex/issues/222>
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by eksperimental** [comment]
oopsy daisies!
