### ISSUE TITLE
Show which requirements did not match in case of conflicts

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex#225]
For example, if you get a conflict:

```
Conflict on ecto 2.0.0-rc.1
  mix.exs: ~> 2.0.0-rc.1
  phoenix_ecto 3.0.0-rc.0: ~> 2.0.0-rc
  timex_ecto 1.0.3: ~> 1.1 or ~> 2.0
```

It is hard to know exactly which one matches and which one does not. It would be nice to print (ok) or a check sign for those that match. And optionally use colors to enhance the experience.

**Comment by josevalim** [comment]
Here are the deps for the example above:

```
      {:ecto, "~> 2.0.0-rc.1"},
      {:phoenix_ecto, "~> 3.0.0-rc.0"},
      {:timex_ecto, "~> 1.0.3"},
```

**Comment by adamkittelson** [comment]
In this instance timex_ecto is has the unresolveable dependency on ecto, it's mix.exs as of 1.0.3 is https://github.com/bitwalker/timex_ecto/blob/b47771c167a354f48ecceb1ae9c8c6ce0a1d5358/mix.exs

**Comment by ericmj** [comment]
We can do this for singular version failures, but sometimes we collect a bunch of failed versions and show them and then it gets tricker. As an example:

```
Conflict on ecto form 1.1.0 to 1.1.4
  mix.exs: ~> 2.0.0-rc.1
  phoenix_ecto 3.0.0-rc.0: ~> 2.0.0-rc
  timex_ecto 1.0.3: ~> 1.1 or ~> 2.0
```

Should we mark as red if the requirement doesn't match a single version or should we only mark if it fails on all versions? Or maybe do red for failed on all, yellow for partial failure and green if it matches all tried versions?

**Comment by josevalim** [comment]
What if we pick just one from ecto 1.1.0 to 1.1.4? We can either, pick one and not say so in the error message. Show the range but say for each we are showing errors. Examples:

```
Conflict on ecto 1.1.4
  mix.exs: ~> 2.0.0-rc.1
  phoenix_ecto 3.0.0-rc.0: ~> 2.0.0-rc
  timex_ecto 1.0.3: ~> 1.1 or ~> 2.0
```

or:

```
Conflict on ecto from 1.1.0 to 1.1.4
Showing failed requirements for 1.1.4
  mix.exs: ~> 2.0.0-rc.1
  phoenix_ecto 3.0.0-rc.0: ~> 2.0.0-rc
  timex_ecto 1.0.3: ~> 1.1 or ~> 2.0
```

I prefer the former but there may be good reasons for the latter.

**Comment by ericmj** [comment]
I will go ahead with showing for all versions If people are confused with the output we can revisit and see if we can simplify it. Here's an example of what it looks like:

<img width="820" alt="screen shot 2016-04-22 at 00 09 48" src="https://cloud.githubusercontent.com/assets/316890/14725873/c375ee2e-081e-11e6-993e-712686391ce1.png">

**Comment by josevalim** [comment]
Thanks @ericmj, I don't think the message above is clear though. Quick question: when conflict resolution fails, it fails only with a single project or it could be with multiple of them? For example, could you possibly show "Conflict on X", "Conflict on Y", "Conflict on Z"?

**Comment by ericmj** [comment]
It can be multiple projects since resolution doesn't fail at a single point. We try a bunch of different combinations of packages and versions, if a combination fails to resolve we will try the next combination. The errors we display are a condensed view of the conflicts that caused a certain combination of packages to fail.

To explain the errors in the screenshot above:

We have conflicts on `ecto`, the conflicts were between version `2.0.0-beta.0` and `2.0.0-rc.1`. Under the error we show the parents of `ecto` and the parents' requirements on `ecto` (there can be more parents but these are the parents we had seen when the resolution failed).

Versions `2.0.0-beta.0` to `2.0.0-rc.0` of `ecto` had the same parents and the same requirements from the parents so we condensed them into a single conflict.

Version `2.0.0-rc.1` of `ecto` is shown separately because it has a different set of parents.

I really appreciate the feedback on this because it's really hard for me to know what are useful messages because I obviously already know what the error message means.

**Comment by ericmj** [comment]
We can do subset checks on the parents to reduce the number of displayed conflicts. The second displayed conflict is a strict superset of the first one (it only adds `timex_ecto`) so they could be merged.

**Comment by josevalim** [comment]
Ok, I am trying to think how to include more information so it helps developers when they first encounter it but it is not verbose on the long term when they already know it.

**Comment by josevalim** [comment]
After a quick Skype, we decided to try the following:

```
Failed to use "ecto" (versions 1.1.0 to 1.1.4) because:
    phoenix_ecto 3.0.0-rc.0 requires ~> 2.0.0-rc
    timex_ecto 1.0.3 requires ~> 1.1 or ~> 2.0
    You specified ~> 2.0.0-rc.1 in your mix.exs

** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock)
```

We have also agreed we should not show failures that come from the "mix.exs".

**Comment by ericmj** [comment]
I have added merging of subset and the new format for conflict error messages:

<img width="850" alt="screen shot 2016-04-23 at 00 12 30" src="https://cloud.githubusercontent.com/assets/316890/14756242/24c4832e-08e8-11e6-8747-0bbb7a376f02.png">

WDYT?

**Comment by ericmj** [comment]
Also, if the coloring of requirements is confusing we can add a text that explains them like we do for `mix hex.outdated`.

I do think we need the yellow color, we could maybe replace it with red but it doesn't make sense to make it green. And I think coloring based on a single failing version of "ecto" will be just as confusing.

**Comment by adamkittelson** [comment]
I like it, easy at a glance with this iteration to see which dependencies are specifying versions compatible with what's in your mix.exs and which aren't.

What happens color-wise in this example if ecto wasn't specified in the application mix.exs?

**Comment by ericmj** [comment]
The above conflicts were generated with these dependencies in the mix.exs file:

```elixir
[{:timex_ecto, "1.0.3"},
 {:ecto, "2.0.0-rc.1"},
 {:phoenix_ecto, "3.0.0-rc.0"}]
```

By removing ecto from mix.exs we get a quite different error message:

```elixir
[{:timex_ecto, "1.0.3"},
 {:phoenix_ecto, "3.0.0-rc.0"}]
```

<img width="836" alt="screen shot 2016-04-23 at 00 31 07" src="https://cloud.githubusercontent.com/assets/316890/14756582/b699db80-08ea-11e6-94b4-fb91cfe9237a.png">

When ecto is not declared in mix.exs the ecto 2.0 versions are never tried in the resolver because timex_ecto immediately restricts it to `~> 1.1`.

**Comment by adamkittelson** [comment]
Cool thanks, I was just curious how it decided which dependency to make green and which to make red in the absence of the version specification in the application's mix.exs. I'm assuming it went with timex's ecto specification because it was first in the list?

**Comment by ericmj** [comment]
No, the color is based of on if the requirement matches the version of the package that was tried.

If we look at the screenshot above we can see that ecto versions 1.1.0 to 1.1.5 was tried. Two packages depend on ecto (we call these packages parents). `phoenix_ecto 3.0.0-rc.0` declared the dependency `{:ecto, "~> 2.0.0-rc2"}`, we color this requirement red because it doesn't match any of the tried ecto versions. `timex_ecto 1.0.3` declared `{:ecto, "~> 1.1 or ~> 2.0"}`, this is colored green because it matches all the ecto versions we tried.

Does that make sense?

**Comment by adamkittelson** [comment]
Yep, I guess what I meant is how does it decide which version of the package to try? I assumed it tried timex_ecto's ~> 1.1 requirement rather than phoenix_ecto's ~> 2.0.0-rc because timex_ecto came before phoenix_ecto in the list.

**Comment by ericmj** [comment]
> Yep, I guess what I meant is how does it decide which version of the package to try?

Well... that's a bit more complicated, to explain that we have to delve into how the resolution algorithm is implemented. My talk at ElixirConf 2014 very roughly explains how it works but the best way to understand it is to read the code of `resolver.ex`.

> I assumed it tried timex_ecto's ~> 1.1 requirement rather than phoenix_ecto's ~> 2.0.0-rc because timex_ecto came before phoenix_ecto in the list.

Yes, it goes in order of dependency definition in mix.exs and then in a breadth-first fashion when recursing into child dependencies.

**Comment by adamkittelson** [comment]
Rad, thanks Eric.

**Comment by josevalim** [comment]
@ericmj it looks perfect. How does it look when the mix.exs comes from a (local) dependency? Also, avoid using colors like orange and yellow and pink because IIRC they don't look good in white background terminal.

**Comment by ericmj** [comment]
> How does it look when the mix.exs comes from a (local) dependency?

Not sure what you mean, like in an umbrella or path dependency?

> Also, avoid using colors like orange and yellow and pink because IIRC they don't look good in white background terminal.

Good point, will doing some testing against white background.

**Comment by ericmj** [comment]
I think the yellow is ok, it's the same we use for evaluation results in iex.

**Comment by ericmj** [comment]
Changes are pushed to master. Please try out master and see what you think (install development of hex with `mix install` from the hex repository directory).
