### ISSUE TITLE
Some warnings when building a package should be errors

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#267]
A `--ignore-warnings` flag can be added to ignore the warnings.

See: https://github.com/elixir-lang/elixir/issues/5047

**Comment by milmazz** [comment]
@ericmj Hi, at the end the flag will be `--ignore-warnings`, which looks to broad, or the more specific `--ignore-non-package-deps`?

**Comment by ericmj** [comment]
I have been thinking some more about this and I think we shouldn't even have a warning override. You should be able to solve it with `:only` and environment matching. All current warnings except "Missing files" should be errors.

If someone in the future reports issues with this we can look at their use case specifically.

What do you think about this approach?

**Comment by milmazz** [comment]
@ericmj I agree with you, we should encourage good packaging practices and with that in mind, we should convert all the current warnings into errors.

In which situation is valid to publish a package with missing files? By default a missing file in a package must be an error, right?

BTW, is there a way to report that a package has *path dependencies* for example?

**Comment by ericmj** [comment]
It's not necessarily an error because by default we include some files such as `src/`, `README.md` and so on. Package publishing should not fail if you have no fails in `src/`. Maybe we should only error if you have explicitly set the files to include?

**Comment by milmazz** [comment]
> Package publishing should not fail if you have no fails in `src/`

In that case, a package that does not include a `LICENSE` file in the root directory is still valid, right? What happens when the `:license` meta tag is not enough? I think that we need to provide also access to the LICENSE details in case we want to know more about it. 

I think that we need at least a minimum set of required files. As far as I remember when you build a Debian package you need to include a minimum set of files under the `debian` directory (e.g. `control`, `copyright`, `changelog`, `rules`, etc.)

> Maybe we should only error if you have explicitly set the files to include?

Yes, but I think that we also need a minimum set of required files. 

@ericmj Please let me know what do you think.

**Comment by ericmj** [comment]
> In that case, a package that does not include a LICENSE file in the root directory is still valid, right? What happens when the :license meta tag is not enough? I think that we need to provide also access to the LICENSE details in case we want to know more about it.

Why is the license field not enough? Many projects do not have a LICENSE file (for example this project). If you want more details you can always go the repository of the package.

> I think that we need at least a minimum set of required files. As far as I remember when you build a Debian package you need to include a minimum set of files under the debian directory (e.g. control, copyright, changelog, rules, etc.)

This is tricky because we want to support any language. I have a hard time seeing files that would be absolutely required for any package.
