### ISSUE TITLE
maintainer contact

### ISSUE THREAD

**Issue by benoitc** [hexpm/hex#282]
A nice to have for hex would be having a way to contact the maintainer so we can ask him to eventually upgrade a release. Maybe just a way to request an upgrade or signal a bug would be cool.

For example packages like [eleveldb](https://hex.pm/packages/eleveldb) are outdated. We have no maintainer email. This package is probably also not official since the official sources have other dependencies and do not contain any hex metadata so it's impossible to ask for an update or track other changes.

**Comment by ericmj** [comment]
We are going to make package ownership information public with username and email of the owners (the email can be hidden if you want). It's a long term effort though because we first have to add logins to the website and update the privacy policy with a grace period where people can opt-out of showing their email.

Currently the best way to get in contact with a package owner (if it's impossible to find contact information in any other way) is to email support@hex.pm.
