### ISSUE TITLE
Proposal: Add public API to determine if a package is outdated

### ISSUE THREAD

**Issue by rrrene** [hexpm/hex#303]
As mentioned in #302, I used undocumented APIs to provide an outdated check to [Credo](https://github.com/rrrene/credo). I wasn't a good citizen here, since this reliance on APIs which weren't intended for me broke my code in the end. Sorry about that!

I really like the idea of Credo checking if it runs the newest version of itself, so I wanted to propose an official API which enables users to check if they have the newest version of a package. From my perspective, the cleanest way to achieve this would be to allow people to request all versions of a given package (or a list of packages, maybe?).

``` Elixir
 # maybe a function which returns a list of version strings

Hex.Registry.package_versions("credo")

# or maybe an API for the information already provided by the JSON API on hex.pm

Hex.Registry.package_info(["credo", "poison"])
```

What do you think? Is this a valid use case to have an offically supported API for?

**Comment by ericmj** [comment]
We can add a public API but it's a bit tricky since Hex is pre 1.0 and you don't know really have a way to control the Hex version you use from a project config or even what version is installed on your machine.

For Credo's use case you also need to handle if Hex is not installed or if Credo is used as a git dependency.

**Comment by ericmj** [comment]
I think for now it's better to use the HTTP API like Credo currently does.
