### ISSUE TITLE
Using hex as the API client for hex_web?

### ISSUE THREAD

**Issue by PragTob** [hexpm/hex#332]
Hello and of course as always thanks for all your work :)

Is hex, as the current project goal, intended to also be used as an API client for hex.pm? E.g. there is the basic Hex.API name space with some nice convenience functions :)

Or would I be better off implementing my own API wrapper referring to the [API spec](http://docs.hexpm.apiary.io/#)?

That is given I want to implement a Phoenix application that relies on data from hex.pm for a lot of what it does, as a use case :)

Thanks for the great work, keep it up, love it :heart: 
Tobi

**Comment by josevalim** [comment]
Given that `hex` is installed as an archive, I believe a proper API client should be a separate project, that is properly versioned, and can be added as a dependency of your project (since an archive can't be really versioned alongside your projects).

**Comment by wojtekmach** [comment]
For reference, this issue came up a couple of times already:

- https://github.com/hexpm/hex/issues/303
- https://github.com/hexpm/hex/issues/302#issuecomment-257038528

**Comment by PragTob** [comment]
Okay, great thanks :)

**Comment by PragTob** [comment]
I did see #303 but that made it sound to my eyes more that it's a thing of hex not being 1.0 yet and the other concerns about the version being installed/it being a git dependency don't matter for me as it would be one application that runs and I maintain so I would have control over the hex version being installed there.

Overall, it makes sense to have a separate API client and if it's good it might even be used by hex at some point I guess :)

**Comment by ericmj** [comment]
When Hex is 1.0 you will probably be able to call some public functions on Hex but we will probably not expose general purpose API functions. Instead there will be some functions around dependency handling and Mix integration, for example functions around the registry, these functions can be useful if your project integrates with Mix dependencies in some way. Even so, I still think all of those functions should be in a separate project that you can properly version, remember that there is currently no way for you to install a specific Hex version, it's always the latest version.

I will list a few reasons why I think calling the Hex application from user application is bad:

1. There is no way to declare that you depend on Hex, adding it to deps will cause conflicts.
2. No way to declare the version of Hex you depend on.
3. Hex uses httpc as HTTP client, not something I would recommend if you can use other clients.
4. The Hex application lifetime and internal state assumes it's being used for dependencies in Hex, it's unclear how it will work from user apps after Mix has run.
5. Internal state is only meant to be used by the end consumer, for example someone can set `HEX_UNSAFE_REGISTRY=1` because they use a private repo, this will cause all your calls to hex.pm to not verify the signature.

The best thing would be if could pull out the HTTP api and registry handling in the Hex client to a shared project. The reason we haven't done this is yet is because we haven't figured out a good way to vendor dependencies in archives. Archives do not support normal mix dependencies today.

**Comment by PragTob** [comment]
@ericmj ah I feared that archives wouldn't support normal mix dependencies :( Well if a workable solution for that comes around it'd be nice to know. If I start this project (which as always is uncertain) I'll probably rip out the HTTP part from here and first put it as a project into an umbrella and when I have a first version up and running move it to its own repo and package.

Thanks for the quick feedback and explanations everyone! :)

**Comment by wojtekmach** [comment]
> The reason we haven't done this is yet is because we haven't figured out a good way to vendor dependencies in archives. Archives do not support normal mix dependencies today.

@ericmj can archives support local deps, as in: `path: "hex_client"`? If so, what we could do in the meantime is:

1. add a new package, e.g. github.com/hexpm/hex_client and publish it on hex.pm. it should probably have a pluggable HTTP library so Hex can use `:httpc` but folks might want to use HTTPoison or something.
2. add hex_client as git submodule to github.com/hexpm/hex. Anytime there's a new Hex release we'd bump the vendored `hex_client` to be the latest tested version.

**Comment by wojtekmach** [comment]
I got it to work with git submodule but Instead of using it as a mix dep, I've adjusted compile path, see: https://github.com/hexpm/hex/tree/wm-hex-client

**Comment by ericmj** [comment]
We could add support for dependencies when building archives in mix. The main problem is that the archive and all its dependencies are loaded in the same runtime where user applications are running. So if the archive and a user app shares a dependency they are going to conflict with conflicts such as duplicate application names, process registered with same names and duplicate module names.

That means that we either need clear boundaries in Mix for when Mix starts calling into Hex and when it's done calling into Hex so that Hex can load/start itself and unload itself when Mix is done (like we do here: https://github.com/hexpm/hex/blob/master/mix.exs#L73). There are no such boundaries today but I think it's possible to add.

The other alternative is the "vendoring" I've been talking about before. By vendoring a dependency in an archive I mean that we use the dependency in a way that there are no conflicts. That might mean that we have a script that copies all source files of the dependency into the Hex project and the script rewrites everything that can conflict, such as modules names, app names, process names, ets tables etc.

**Comment by wojtekmach** [comment]
>  The main problem is that the archive and all its dependencies are loaded in the same runtime where user applications are running. So if the archive and a user app shares a dependency they are going to conflict with conflicts such as duplicate application names, process registered with same names and duplicate module names.

gotcha, that was the main part I was missing.

**Comment by PragTob** [comment]
Hey there,

just as an update after trying to figure it out for a while, I'll probably write a standalone client. There's other parts of Hex sprinkled over Hex.API which makes extraction harder (especially together with the tests) and given that the only thing I really need (so far) is release/package data this seems to be by far the easier route, although I'd have theoretically liked for it to be the same code :)

Anyhow, thanks for all the help :)

Tobi
