### ISSUE TITLE
mix hex.outdated doesn't seem to take into account version conflicts

### ISSUE THREAD

**Issue by PragTob** [hexpm/hex#347]
`mix hex.outdated` tells me that I can update `phoenix_live_reload`

![selection_052](https://cloud.githubusercontent.com/assets/606517/22208308/bb75bd60-e182-11e6-9d4d-279ca453762b.png)

In reality, I sadly can't. E.g. mix deps.update only sets it to 1.0.6 and trying to set it to 1.0.7 manually yields the following error:

```
tobi@comfy ~/projects/liefery-courier-tracker $ mix deps.get
Running dependency resolution...

Failed to use "fs" (version 2.12.0) because
  mix_test_watch (version 0.2.6) requires ~> 0.9.1
  phoenix_live_reload (version 1.0.7) requires ~> 2.12.0

** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}

```

Ideally hex would take into account such conflicts, and even better tell me which package holds it down :)

Of course, this is an extra bonus feature. For a software gardener like me `mix hex.outdated` is :heart: :green_heart: :purple_heart: :tada: :dancer: :burrito:  - thanks for all your awesome work!

**Comment by ericmj** [comment]
I agree that this would be a nice feature. Unfortunately it's very complex to understand why an upgrade is not possible. I would say that `mix deps.get` shows in a nice way why the upgrade failed.

As an example of the complexities, `hex.outdated` may show two packages as updatable, but you can only update one or the other because updating both would cause conflicts. How should this be displayed in the `hex.outdated` UI?

It may also be that `mix deps.get` failed because of multiple conflicts, conflicts that may have come from different backtracks the resolver made. So even though `phoenix_live_reload` showed up as one the reasons why the resolution failed it may not be what you should fix to make it resolvable.

But I don't want to write this off as impossible, or maybe we can do some improvements to the flow. Can you share your deps and lock that produced this so I can try your scenario?

**Comment by PragTob** [comment]
Thanks for the fast answer! Sure [here is the mix.lock](https://gist.github.com/PragTob/d2395968ff0807d0430b67ac520714ef)

I agree, the complete solution for this is probably rather complicated (and my thinking is probably to simple as I never wrote a dependency graph resolver). Personally I'd also be happy with a simple solution that covers msot use cases or not as accurately as possible.

I agree, the `mix deps.get` message I got is :+1: btw.!

> As an example of the complexities, hex.outdated may show two packages as updatable, but you can only update one or the other because updating both would cause conflicts. How should this be displayed in the hex.outdated UI?

Imo `hex.outdated` doesn't need to show anything here. I mean if it did, it'd be amazing. But if I update one of the 2 and it just starts showing the error afterwards that is good enough imo and already a good improvement.

> It may also be that mix deps.get failed because of multiple conflicts, conflicts that may have come from different backtracks the resolver made. So even though phoenix_live_reload showed up as one the reasons why the resolution failed it may not be what you should fix to make it resolvable.

Hm this is an interesting one. I dunno how many times this triggers/how the values are gathered inside of hex but my first reflex would be to just mark every package as "possible conflict with all these others packages" or something, then again that might be thinking too simple again.

**Comment by ericmj** [comment]
I have looked at this and it's unfortunately not feasible because we would have to run a full dependency resolution for each outdated where we only upgrade the package. It may also be possible to update the version but not all the way to the latest, which is not clear how to display in the UI.

Because of the technical and UX issues I think (and the ones I listed above) it would be better to keep this feature simple.
