### ISSUE TITLE
Add --repo option to `mix hex.info PACKAGE`

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex#362]
currently `mix hex.info PACKAGE [VERSION]` only works for `hexpm` repo, we should allow it for other ones as well. cc @ericmj

**Comment by ericmj** [comment]
I don't it's possible with how things work right now because `hex.info` uses the HTTP API and we don't have store a API url for repos. This is mainly because we haven't yet addressed how to publish to multiple repos yet - only how to consume packages from multiple repos.

I think when we can publish to other repos without manually setting the API url we will solve this as well. Another alternative is to change `hex.info` to use the registry instead of the API, but that won't work for `hex.search` which has the same issue.

**Comment by ericmj** [comment]
Ah, it looks like we cannot use the registry for `hex.info` without removing features. Lets revisit this when we have implemented multi-repo for publish.
