### ISSUE TITLE
Multiple Repos Question

### ISSUE THREAD

**Issue by ninjanicely** [hexpm/hex#377]
I've got a hello world project and the only change to it is I'm including ex_doc as a dependency. 
I've specified this dependency to come from the repo hexpm...
`{:ex_doc, ">=0.0.0", repo: :hexpm}`

My problem is, I'm trying to publish to a private repo (I've specified this through the api_url in the hex.config).

When I try and publish the hello world project, I get a ..

Publishing failed
Validation error(s)
  requirements:
    ex_doc: package does not exist

Now, if I add the param `only: :dev` to the dependency above, I can publish fine (as well as pull down the package in other projects).

That's fine for ex_doc, but what if I want to use a package in prod, this doesn't work as a solution.

I know the previous philosophy was a package in the public repo should be build-able (with regards to dependencies) from a single repo, but is that philosophy the same for my private repo? Is there some kind of flag I can set to say: "Hey, this is going in my private repo, I understand it might not build if pulled down." sort of thing?

Or is the only alternative to port all the public packages I need into my private repo? <- Not a great solution either.

**Comment by ericmj** [comment]
The validation error you are seeing is returned from the server. You need to make sure the repository you are using supports packages from other repositories. If you are using hexpm as your repository this will not work since it was built for https://hex.pm which will not allow this. You need to build your own repository or modify the repository you are using to support this.
