### ISSUE TITLE
Get elixir-lang docs with mix hex.docs fetch

### ISSUE THREAD

**Issue by 2kodes** [hexpm/hex#388]
hi,
 is there any way to get the docs for elixir-lang through hexdocs?? something like mix hex.docs fetch elixir

mix hex.docs fetch elixir
 ** (Mix) No package with name elixir
 
mix hex.docs fetch elixir-lang
** (Mix) No package with name elixir-lang

**Comment by ericmj** [comment]
This is not possible since elixir is not a Hex package so we don't know what version to fetch.

**Comment by josevalim** [comment]
@ericmj I think it would be worth special casing mix, elixir, logger, iex, eex and ex_unit. You can get the version the script is currently running on. Thoughts?

**Comment by ericmj** [comment]
Yeah, we can get the current version, for builds on branches I think it would be hard but it's probably not the end of the world it that doesn't work. It would also be a slight difference behaviour from packages since they always fetch the latest version.

We also need to make sure we build the doc tarballs for elixir which seems to be broken or not implemented right now.

**Comment by ericmj** [comment]
We build tarballs for elixir core docs now. This issue is up for grabs.
