### ISSUE TITLE
Simplify organization commands

### ISSUE THREAD

**Issue by mgartner** [hexpm/hex#455]
I'm finding the process of setting up access to private packages unnecessarily confusing. In particular, I don't see any benefit from having an additional step of running `mix hex.organization auth NAME`. As long as the user has logged-in with `mix hex.user auth` and they have access to the organization, then they should be able to read/write packages.

Is there a technical reason why `mix hex.organization auth NAME` is necessary, if the user has already logged-in?

Additionally, I find it odd that `mix hex.organization auth NAME` requires the organization's name in the command, while `mix hex.user auth` does not require the user's name. If the former command is necessary for organizations to work, it would be nice if these were consistent, and I think it would save people time.

**Comment by josevalim** [comment]
> Additionally, I find it odd that mix hex.organization auth NAME requires the organization's name in the command, while mix hex.user auth does not require the user's name.

Isn't this an apples to oranges comparison in the sense that none of them require the user name to be given? After all, you don't authenticate an organization, you authenticate a user inside an organization. Or do you mean we should have a prompt that asks the organization name?

I think however that the commands should avoid using NAME since it is ambiguous, `mix hex.organization auth ORGANIZATION` is definitely clearer.

In any case, it probably doesn't hurt to authenticate the user and all of his organizations on `hex.user auth`. If that's undesired, we could have a `--skip-organizations` flag. @ericmj, do we deauth the organizations if the user deauths?

**Comment by ericmj** [comment]
> Isn't this an apples to oranges comparison in the sense that none of them require the user name to be given? After all, you don't authenticate an organization, you authenticate a user inside an organization. Or do you mean we should have a prompt that asks the organization name instead of it being a task argument?

I also don't understand what the difference is here. The reason we have the name on the command line for organizations is because you have to be able to run it in scripts which is necessary for build/CI servers. The reason user authentication prompts is because your username and email can potentially be private and not something you want persisted in your shell history.

> I think however that the commands should avoid using NAME since it is ambiguous, mix hex.organization auth ORGANIZATION is definitely clearer.

:+1:

> In any case, it probably doesn't hurt to authenticate the user and all of his organizations on hex.user auth. If that's undesired, we could have a --skip-organizations flag. @ericmj, do we deauth the organizations if the user deauths?

I think we can do this, I will elaborate below on how things work today and why they work like this. If we add this we have to deauth orgs when the user deauths 👍.

`mix hex.user auth` and `mix hex.organization auth` are two different permission levels. When you have authenticated as a user you can do administrative actions; publish packages, add/remove owners, retire packages, etc.

You can authenticate the user and the organization without authenticating other, for example on a build server or CI server you would only authenticate the organization.

When you authenticate to anything we generate a key with specific permissions, the user key has API access and the organization key has repository access. You could think that the user key should have access to the repository also but the main reason they are separate is that the user key is encrypted, to publish a package you have to supply your passphrase to decrypt your API key, it would be annoying to give your passphrase every time you run `mix deps.get` and it wouldn't be viable in CI scripts.

I think an acceptable solution would be that when you authenticate as a user we also create organization keys for all organizations you are member of. The downside is that when you are added to new repositories after having authenticated on a machine you would still have to manually run `mix hex.organization auth` because each repository has a distinct key, I'm not sure if this could/should happen automatically.

**Comment by ericmj** [comment]
Another solution would be to create a permission level for keys where the key has access to all repositories the user is a member of. This is less secure but may be acceptable for the convenience of not having to manually authenticate orgs you have been added as a member to.

**Comment by mgartner** [comment]
> Another solution would be to create a permission level for keys where the key has access to all repositories the user is a member of. This is less secure but may be acceptable for the convenience of not having to manually authenticate orgs you have been added as a member to.

Can you explain why this is less secure? 

In my mind permissions and access levels should be managed on the server side. From the client perspective, all I should have to do is verify that I am me, with my username/email and password. Once I am authenticated as a user, hex.pm should be deciding what packages and organizations I can read or write from.

> ...the main reason they are separate is that the user key is encrypted, to publish a package you have to supply your passphrase to decrypt your API key...

Can you explain more about this? Is this a signature step? Where is the key encrypted?

**Comment by ericmj** [comment]
> Can you explain why this is less secure?

Say that you are a member of two organizations, one is SuperSecretAgency and the other is NotReallySecretOrg. If someone manages to gain access to your NotReallySecretOrg key they also gain access to SuperSecretAgency.

> In my mind permissions and access levels should be managed on the server side. From the client perspective, all I should have to do is verify that I am me, with my username/email and password. Once I am authenticated as a user, hex.pm should be deciding what packages and organizations I can read or write from.

Permissions are managed on the server side, the only thing the client sees are opaque key strings. The problem is storing a plaintext key on your machine that forever gives you access to your entire account.

> Can you explain more about this? Is this a signature step? Where is the key encrypted?

It is encrypted on the client so that it is harder for an attacker to steal your publish key. This also defeats known vulnerabilities in other package managers such as: https://www.infoq.com/news/2016/03/npm-infection.

**Comment by mgartner** [comment]
> Permissions are managed on the server side, the only thing the client sees are opaque key strings. The problem is storing a plaintext key on your machine that forever gives you access to your entire account.

What if when I run `mix hex.user auth`, the server issues me an API key that I can revoke at any time from the web UI?

> It is encrypted on the client so that it is harder for an attacker to steal your publish key. This also defeats known vulnerabilities in other package managers such as: https://www.infoq.com/news/2016/03/npm-infection.

Given that publishing is a relatively infrequent command, maybe require a password for this command, and the key only grants read permission?

**Comment by ericmj** [comment]
> What if when I run mix hex.user auth, the server issues me an API key that I can revoke at any time from the web UI?

That doesn't really solve the problem, you can already revoke your keys, and it assumes you know when your key is stolen.

> Given that publishing is a relatively infrequent command, maybe require a password for this command, and the key only grants read permission?

We already have this. We have one publish key that requires a password and one read-only key that does not require password. What's the practical difference between your proposal and what I proposed above?

**Comment by mgartner** [comment]
> We already have this. We have one publish key that requires a password and one read-only key that does not require password. What's the practical difference between your proposal and what I proposed above?

Sorry I misunderstood your earlier comment then.

> Say that you are a member of two organizations, one is SuperSecretAgency and the other is NotReallySecretOrg. If someone manages to gain access to your NotReallySecretOrg key they also gain access to SuperSecretAgency.

I guess you have to decide that keeping read-only access separate if a user key is stolen is worth the added steps and confusion of multiple logins. Given that these keys are all stored in the same file anyway (I think), wouldn't it be likely that if 1 was stolen, then more would be as well?

Btw, thanks for filling in some of the technical details here. I obviously don't have a lot of insight into the details or why decisions were made, and I hope I'm not unecessarily pestering you—after using organizations for a handful of weeks I just have a feeling that its unecessarily cumbersome, but that may be required. I've not felt the same frustrations in other package managers, which is why I brought it up to begin with.

**Comment by ericmj** [comment]
> I guess you have to decide that keeping read-only access separate if a user key is stolen is worth the added steps and confusion of multiple logins. Given that these keys are all stored in the same file anyway (I think), wouldn't it be likely that if 1 was stolen, then more would be as well?

They will probably all be stolen but the publish key will likely be unusable since it's encrypted with the user's passphrase.

> Btw, thanks for filling in some of the technical details here. I obviously don't have a lot of insight into the details or why decisions were made, and I hope I'm not unecessarily pestering you—after using organizations for a handful of weeks I just have a feeling that its unecessarily cumbersome, but that may be required. I've not felt the same frustrations in other package managers, which is why I brought it up to begin with.

No worries at all, I am very happy for all feedback on organizations, that's why we have the beta. Hopefully the changes I proposed above will make it less cumbersome.

I will summarize my proposed changes:

* Create a new key type on the backend with a permission level that will give access to all the user's organizations
* `mix hex.user auth` will also generate this new key type
* Add `mix hex.organization` without a specific `NAME` that will generate the new key type if a user is authenticated on the machine

**Comment by ericmj** [comment]
In the future we should also give keys a maximum lifetime with automatic renewal to alleviate some of the security concerns I raised, but this is a separate and much bigger task.

**Comment by ericmj** [comment]
As a first step we have added prompts when we detect that we require authentication we ask for the credentials immediately instead of telling the user to run `mix hex.user auth` or `mix hex.organization auth`.

This should make the workflow better and cause less interruptions. We are still discussing if we want to create a single key for all organizations. Another possible solution is to create separate keys for all organizations you are member of when you run `mix hex.user auth`. For the user it should be very little difference in practice between separate keys or a single shared key.

**Comment by mgartner** [comment]
Awesome! 👍

**Comment by ericmj** [comment]
We also automatically auth all your organizations when you run `mix hex.user auth` now. We will see how this works for now and then review later and see if we need to make other improvements. Thanks for your feedback.
