### ISSUE TITLE
Documentation for private packages?

### ISSUE THREAD

**Issue by madshargreave** [hexpm/hex#459]
Hi

I am trying to publish a library under an org, but I get this error

```
publishing docs for private packages is disabled
```

Can it be true that private packages does not support docs?

**Comment by wojtekmach** [comment]
That's right, we don't allow to publish docs for private packages yet but its on the roadmap in https://github.com/hexpm/hexpm/issues/537. It's a bit tricky because all content on hexdocs.pm is public, however we need to protect docs for private packages by auth.

You can publish package without docs by doing: `mix hex.publish package`

**Comment by madshargreave** [comment]
Thanks for the quick response

Is there any ETA on this functionality?

**Comment by ericmj** [comment]
The billing functionality will ship around the end of the year, after billing is out private documentation is the top priority.

**Comment by madshargreave** [comment]
Thanks, looking forward
