### ISSUE TITLE
Getting amqp (Hex package) ** (ArgumentError) argument error

### ISSUE THREAD

**Issue by nirmannarang** [hexpm/hex#469]
While running **make all** step for RabbitMQ Server 3.7.0, I am getting the following error:

`Putting child 0x95a5d000 (escript/rabbitmqctl) PID 20257 on the chain.
Live child 0x95a5d000 (escript/rabbitmqctl) PID 20257
 GEN    escript/rabbitmqctl
Resolving Hex dependencies...
Dependency resolution completed:
  amqp 0.2.4
  csv 2.0.0
  dialyxir 0.5.1
  json 1.0.2
  parallel_stream 1.0.5
  simetric 0.2.0
  temp 0.4.3
* Getting amqp (Hex package)
** (ArgumentError) argument error
    (stdlib) re.erl:734: :re.run("https://repo.hex.pm/tarballs/amqp-0.2.4.tar", {:re_pattern, 1, 0, 0, <<69, 82, 67, 80, 91, 0, 0, 0, 0, 0, 0, 0, 81, 0, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255, 47, 0, 64, 0, 0, 0, 1, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>}, [{:capture, :all, :index}, :global])
    (elixir) lib/regex.ex:590: Regex.do_replace/4
    (hex) lib/hex/scm.ex:103: Hex.SCM.update/1
    (hex) lib/hex/scm.ex:150: Hex.SCM.checkout/1
    (mix) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
    (mix) lib/mix/dep/converger.ex:180: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:189: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:119: Mix.Dep.Converger.all/7
Reaping losing child 0x95a5d000 PID 20257
Makefile:73: recipe for target 'escript/rabbitmqctl' failed
make: *** [escript/rabbitmqctl] Error 1
Removing child 0x95a5d000 PID 20257 from chain.`

**Comment by josevalim** [comment]
What is your Elixir and Erlang versions? Can you please run `mix hex.info` and paste the output here?

**Comment by nirmannarang** [comment]
`Hex:    0.17.1
Elixir: 1.5.2
OTP:    20.0

Built with: Elixir 1.5.1 and OTP 18.3
`

**Comment by nirmannarang** [comment]
@josevalim Any update on what could be wrong here?

**Comment by josevalim** [comment]
Thanks for the info, @nirmannarang. We have no news for now, once we do, we will post them here.

**Comment by ericmj** [comment]
@josevalim Is this the same error that happens when you compile with an Elixir that doesn't support the regex changes in OTP20?

It shouldn't happen since we built with Elixir 1.5.1 though...

**Comment by ericmj** [comment]
@nirmannarang Can you show us steps to reproduce the error? What project are you running this and what commands are you running.

**Comment by nirmannarang** [comment]
@ericmj 
#Built and Installed Erlang OTP 20.0 from source

#Built and installed elixir
git clone https://github.com/elixir-lang/elixir
cd elixir
git checkout v1.5.2
make
sudo make install

#Build RabbitMQ Server 3.7.0
wget https://github.com/rabbitmq/rabbitmq-server/archive/v3.7.0.tar.gz
tar xf v3.7.0.tar.gz
cd rabbitmq-server-3.7.0
make all

It fails at **make all** step.

**Comment by ericmj** [comment]
I cannot reproduce this error. This regex error usually means that you are using an Elixir version that is not compatible with OTP 20 or using Elixir code that was built an incompatible Elixir version. Make sure you are using OTP 20, Elixir 1.5.2 and Hex 0.17.1.

**Comment by nirmannarang** [comment]
@ericmj 
It is strange to me too as Elixir, Hex, OTP versions which I am using are all compatible.
Can you please direct me to the issue you know about? Maybe I can make some changes to get the build successful, at least.

**Comment by ericmj** [comment]
I looked around but it doesn't seem to be really documented anywhere. With OTP 20 the way we precompile regexs during compilation broke because OTP updated the regex version they are using. This means that regexs compiled with OTP 19 did not work with OTP 20 and vice versa. We fixed this in Elixir 1.5.0.

I think this is the issue you are seeing but you shouldn't be getting it with the versions you are using so I'm not really sure what is happening.

**Comment by onfiro** [comment]
Hey! I have similar ptoblems when build RabbitMQ  3.7.0 from source.
Hex:    0.17.3
Elixir: 1.6.1
OTP:    20.1

Built with: Elixir 1.5.3 and OTP 18.3

**Comment by ajaygtm71** [comment]
Facing similar issue on rabbitmq 3.7.3 with hex.info as 
Hex:    0.17.3
Elixir: 1.6.1
OTP:    20.0.4

Built with: Elixir 1.6.1 and OTP 20.0.4

output:
Dependency resolution completed:
  amqp 0.2.4
  csv 2.0.0
  dialyxir 0.5.1
  json 1.0.2
  parallel_stream 1.0.6
  simetric 0.2.0
  temp 0.4.4
* Getting json (Hex package)
** (ArgumentError) argument error
    (stdlib) re.erl:734: :re.run("https://repo.hex.pm/tarballs/json-1.0.2.tar", {:re_pattern, 1, 0, 0, <<69, 82, 67, 80, 91, 0, 0, 0, 0, 0, 0, 0, 81, 0, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255, 47, 0, 64, 0, 0, 0, 1, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>}, [{:capture, :all, :index}, :global])
    (elixir) lib/regex.ex:598: Regex.do_replace/4
    (hex) lib/hex/scm.ex:103: Hex.SCM.update/1
    (hex) lib/hex/scm.ex:163: Hex.SCM.checkout/1
    (mix) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
    (mix) lib/mix/dep/converger.ex:185: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:121: Mix.Dep.Converger.all/7
    (mix) lib/mix/dep/converger.ex:106: Mix.Dep.Converger.all/4
Makefile:85: recipe for target 'escript/rabbitmqctl' failed

**Comment by dumbbell** [comment]
Hi!

I just discussed this issue on IRC with @ajaygtm71. The problem is the copy of the Hex plugin included in the RabbitMQ source archive. The plugin was fetched using Mix when we create the source archive. I suppose the plugin was compiled on x86 so little-endian and it crashes when used on a big-endian host.

To test that theory, @ajaygtm71 built the Hex plugin locally on s390x and copied the `.beam` files to `rabbitmq-server-3.7.4/deps/.mix/archives/hex-0.17.3/hex-0.17.3/ebin` in the source directory. After that, RabbitMQ built and started successfully.

We include the Hex plugin in the source archive because RabbitMQ should still build fine when offline. This is the constraint of most Linux distributions' (and other systems') package builders. A proper solution for us would probably be to include the Hex plugin sources, not a pre-compiled version.

Out of curiosity, does Hex.pm provide a big-endian pre-compiled version of the Hex plugin? I mean, if Mix is executed a on big-endian host, will it fetch an appropriate copy of the Hex plugin?
