### ISSUE TITLE
NPM missing packages and private Hex server

### ISSUE THREAD

**Issue by sashaafm** [hexpm/hex#481]
As you probably know, yesterday NPM had a major problem with disappearing packages as can be seen in this Hacker News [thread](https://news.ycombinator.com/item?id=16087024). Although I haven't fully understood what was the root cause of the problem yet (I believe they haven't published a post mortem yet), I've noticed several people claiming that some "trolling"/malicious packages were published with the same name as those that went missing. This enables malicious users to inject malicious code into users' machines and user-facing systems.

Another problem was that users and organisations who rely on NPM for their build process were unable to build their codebases as they were unable to fetch the required dependencies from NPM.

Therefore I'd like to ask two questions:

1. Is Hex protected against the same problems which NPM faced yesterday? Can malicious users inject malicious packages if something like this happened? (i.e., there's no control of the authenticity of packages by a mechanism like a signing key or per-version hash).
2. Does Hex provide a way to setup our own private Hex servers which cache fetched packages (couldn't find suck information in the website)?  I'd like to suggest such a feature - which some package managers already provide like Maven I think - which I believe would bring greater safety and uptime for the Elixir users and organisations which are betting on Elixir, but also further boost Elixir (and Erlang) as a contender for those which are looking to build good and reliable software.

Thank you so much for your great work 🙇

**Comment by wojtekmach** [comment]
Hello @sashaafm!

> Is Hex protected against the same problems which NPM faced yesterday?

Yes, it' protected, see e.g. this comment https://github.com/hexpm/hexpm/issues/277#issuecomment-201962939. For the time being we still allow a 1h window to re-publish or revert packages, see: https://github.com/hexpm/hexpm/issues/197 but we'll likely eventually remove that. Moreover, each package includes a checksum (stored in `mix.lock`) to ensure you're always downloading the same code for given version.

> Does Hex provide a way to setup our own private Hex servers

Yes, there are two options:

1. Private packages hosted on Hex.pm (currently in beta), see: https://hex.pm/blog/private-packages-and-organizations
2. Self-hosted repositories - you can implement your own Hex-compatible repository according to the specification: https://github.com/hexpm/specifications/blob/master/endpoints.md#endpoints-1, and configure Hex to use them: https://hex.pm/docs/tasks#hex_repo

**Comment by sashaafm** [comment]
> Yes, it' protected, see e.g. this comment hexpm/hexpm#277 (comment). For the time being we still allow a 1h window to re-publish or revert packages, see: hexpm/hexpm#197 but we'll likely eventually remove that. Moreover, each package includes a checksum (stored in mix.lock) to ensure you're always downloading the same code for given version.

Thank you for your clarification. Indeed I was forgetting about the checksum in `mix.lock`, my bad.

> Yes, there are two options:
>
> Private packages hosted on Hex.pm (currently in beta), see: https://hex.pm/blog/private-packages-> and-organizations
> Self-hosted repositories - you can implement your own Hex-compatible repository according to the > specification: https://github.com/hexpm/specifications/blob/master/endpoints.md#endpoints-1, and > configure Hex to use them: https://hex.pm/docs/tasks#hex_repo

Private packages seem to be a good middle-ground to solve this kind of issues. Very happy to see Hex is ahead of other package managers in this regard. 

Thanks a lot @wojtekmach

**Comment by ericmj** [comment]
We got some more details from NPM: http://blog.npmjs.org/post/169432444640/npm-operational-incident-6-jan-2018, but until they release the full technical details it is hard to comment on this.

This seems to have been caused by tooling that tries to prevent spam, fortunately we do not have spam issues on Hex.pm since we do not operate on the same scale as NPM. We do not have automatic tooling that deletes packages,  but we do have checks that tries to detect package squatting but it requires manual intervention by admins and we fortunately haven't had to delete packages for this reason.

Users cannot delete packages but admins can do it, the main reasons being for security or legal reasons. If a package is deleted anyone can publish over it, but we are planning on fixing this: https://github.com/hexpm/hexpm/issues/272. People that have locked a package in their mix.lock will get an error if the package checksums do not match, users that fetch the package for the first time in their project will not get any notification that they are fetching a possibly malicious package.

We do not have caching proxy servers but if we anyone wants to start building one that would be very appreciated and a great addition to the ecosystem. We have public specifications as Wojtek showed for building something like this.

I will comment again if there are any more details from the post-mortem that NPM will publish in the coming days.

**Comment by ericmj** [comment]
NPM published a more detailed incident report: http://blog.npmjs.org/post/169582189317/incident-report-npm-inc-operations-incident-of.

It's hard to protect against human errors so when deleting packages starts to become a common support task we will have to implement detailed procedures on how to delete packages. We have also made the policy stricter for deleting packages so that now we will no longer delete packages on users' support request unless they can show that the package needs to be taken down for legal or security reasons. That will be the only reasons for deleting by user request.

Because of the stricter policy we will keep the 1 hour revert window for package releases and increase the revert window to 24 hours within a package first release to make it easier for developers to delete packages that were published by mistake.

We will also give https://github.com/hexpm/hexpm/issues/272 higher priority.
