### ISSUE TITLE
hex.publish hard wires the path to ex_doc

### ISSUE THREAD

**Issue by pragdave** [hexpm/hex#539]
I'm using `asdf` to manage my elixir versioning. Like most version managers, it generates shims for the executables. In my case:

~~~ shell
~/P/earmark|master
15∙30∙38≻ which ex_doc
/home/dave/.asdf/shims/ex_doc
~~~
 
When I run `mix hex.publish`, it fails:

~~~
Building docs...
** (ErlangError) Erlang error: :enoent
    :erlang.open_port({:spawn_executable, '/home/dave/.mix/escripts/ex_doc'}, [:use_stdio, :exit_status, :binary, :hide, {:args, ["Earmark", "1.2.5", "_build/dev/lib/earmark/ebin", "-m", "Earmark", "-o", "doc", "-p", "https://github/pragdave/earmark.html", "-f", "html", "-n", "-n", "https://hexdocs.pm/earmark/master"]}])
    (elixir) lib/system.ex:629: System.cmd/3
:   :   : 
~~~

Rather than hard-wiring the path to ex_doc, I believe that hex should just assume it is in the path.

Cheers

Dave

**Comment by wojtekmach** [comment]
Hello, hex just runs `mix docs` and I believe the problem is that earmark has "overwritten" docs task:

- https://github.com/pragdave/earmark/blob/v1.2.5/mix.exs#L33
- https://github.com/pragdave/earmark/blob/v1.2.5/mix.exs#L70
- https://github.com/pragdave/earmark/blob/v1.2.5/tasks/docs.exs#L25

I believe there's nothing we can do on Hex side, but let us know if we can help still!

**Comment by pragdave** [comment]
argh... sorry to waste your time.
