### ISSUE TITLE
Regression building nerves system with hex 0.17.6

### ISSUE THREAD

**Issue by erauer** [hexpm/hex#549]
I'm seeing a regression in Hex 0.17.6 vs 0.17.3 when building [nerves_system_rpi3]( https://github.com/nerves-project/nerves_system_rpi3).

running "mix deps.get" works on 0.17.3 but fails on 0.17.6.

$ mix deps.get 
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  distillery 1.5.2
  earmark 1.2.4
  ex_doc 0.18.3
  nerves 1.0.0-rc.1
  nerves_system_br 1.0.0-rc.3
  nerves_system_linter 0.3.0
  nerves_toolchain_arm_unknown_linux_gnueabihf 1.0.0-rc.0
  nerves_toolchain_ctng 1.4.0-rc.0
* Getting nerves (Hex package)
* Getting nerves_system_br (Hex package)
** (MatchError) no match of right hand side value: {:error, :enoent}
    (hex) src/vendored_hex_tarball.erl:317: :vendored_hex_tarball.touch/1
    (hex) src/vendored_hex_tarball.erl:309: :vendored_hex_tarball."-unpack_tarball/2-lc$^0/1-0-"/2
    (hex) src/vendored_hex_tarball.erl:309: :vendored_hex_tarball.unpack_tarball/2
    (hex) src/vendored_hex_tarball.erl:168: :vendored_hex_tarball.finish_unpack/1
    (hex) lib/hex.ex:149: Hex.unpack_tar!/2
    (hex) lib/hex/scm.ex:139: Hex.SCM.update/1
    (hex) lib/hex/scm.ex:176: Hex.SCM.checkout/1

**Comment by wojtekmach** [comment]
That seems to be regression in the new Erlang tarball code we have shipped recently, sorry for that.  will investigate tomorrow, you can downgrade to last good version with:

    mix hex.install 0.17.3

**Comment by ericmj** [comment]
The issue is that the nerves packages have broken symlinks, the links point to non-existent files. The code that breaks in Hex is when we touch all unpacked files so they have the mtime of unpacking. We do this so that incremental compilers will always pick up the latest changes.

The previous code worked because it used `File.touch` that will create the symlink target if it does not exist, so it would create files that were technically not part of the package. Unfortunately there doesn't seem to be a function to update the mtime of a symlink, we have `file:read_link_info` but no `file:write_link_info`.

What should we do here? Do not touch symlinks, create the target file or is there way that I haven't found to touch the symlink but not the target?

/cc @josevalim @mobileoverlord

**Comment by mdillavou** [comment]
I am seeing something similar. 0.17.3 works fine, but 0.17.6 fails:

```
...
* Getting ranch (Hex package)
* Getting pipe (Hex package)
** (ArgumentError) argument error
    :erlang.binary_to_atom('mix', :utf8)
    (elixir) lib/string.ex:1824: String.to_atom/1
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (hex) lib/hex/scm.ex:147: Hex.SCM.update/1
    (hex) lib/hex/scm.ex:176: Hex.SCM.checkout/1
    (mix) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
    (mix) lib/mix/dep/converger.ex:177: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:186: Mix.Dep.Converger.all/9

```

**Comment by wojtekmach** [comment]
just to give some more context, we got that crash when unpacking:

https://github.com/nerves-project/nerves_system_br/blob/master/board/nerves-common/skeleton/dev/log

which points to non-existent `log` in:

https://github.com/nerves-project/nerves_system_br/tree/master/board/nerves-common/skeleton/tmp

**Comment by wojtekmach** [comment]
@mdillavou that's a separate issue, I'm working on that right now.

**Comment by mdillavou** [comment]
ok, I opened a separate ticket #550
