### ISSUE TITLE
Add support for PubGrub

### ISSUE THREAD

**Issue by dennisxtria** [hexpm/hex#552]
PubGrub is a general-purpose version solving algorithm looks very interesting in its implementation and could potentially be useful for hex.

If it is possible, please add support for PubGrub.

[Source](https://medium.com/@nex3/pubgrub-2fb6470504f)

**Comment by josevalim** [comment]
Changing the version solving algorithm is a very complex task and, even if we are going to migrate to something new, we should do a complete study of the algorithms and also wait for the alternatives to get a bit more mileage. At the moment we are focusing on other tasks.

**Comment by ericmj** [comment]
It looks like the PubGrub algorithm is very similar to the Hex resolver both in the core loop and how it generates error messages. The main difference is that PubGrub is based on incompatibilities instead of success constraints which are then used to trim the set of possible dependency combinations to try when backtracking. That's a clever optimization that we should be able to use in Hex as well.
