### ISSUE TITLE
Proposal: Add flag to make hex.outdated return a non-zero code when deps are out of date

### ISSUE THREAD

**Issue by mschae** [hexpm/hex#554]
For our CI Pipeline it would be ideal if `mix hex.outdated` could be configured to return a non-zero exit code if any dependencies are out of date, similar to how one can at `--warnings-as-errors` to `mix compile`.

If this proposal is deemed interesting by the community I would volunteer to implement that functionality.

**Comment by ericmj** [comment]
Yeah, we can definitely add this feature. You can look at `mix hex.audit` for inspiration because it does the same thing.

On a personal note I think that outdated dependencies should not be treated as an error nor as something necessarily bad, but I understand that it can still be a useful for feature 😀.

**Comment by wojtekmach** [comment]
I'm glad you've came around (https://github.com/hexpm/hex/issues/208) 😂

**Comment by mschae** [comment]
Sorry didn't find the earlier ticket. I do agree we wouldn't make our CI pipeline fail, just issue warnings when something's outdated. Still easier for us to check for a non-zero code tho :)

**Comment by ericmj** [comment]
> I'm glad you've came around (#208) 😂

 Yes, I realize it's better to just give my recommendations and let folks do what they want :)
