### ISSUE TITLE
error on publish: "Creating tarball failed: tarball is too big"

### ISSUE THREAD

**Issue by hypno2000** [hexpm/hex#566]
We are trying to publish a forked `ex_admin` under our organization and getting this:

```
Publishing package...
** (Mix) Creating tarball failed: tarball is too big
mix hex.publish  9.31s user 4.45s system 86% cpu 15.956 total
```

We have not added any static assets so it should not be any bigger than the original.

Anyway to get around this?

Thanks

**Comment by ericmj** [comment]
There seems to be some duplication:

web/static/assets/fonts/
priv/static/fonts/

and:

web/static/vendor/
priv/static/js/

A large part of the size also seems to be themes, since ex_admin does not seem to maintain them I would recommend instead giving instructions on how to do download and install them or build a task that does this instead of bundling them in the dependency.

Solving these issues should fix the tarball size issue, make it faster for your users to download the dependency, and reduce their release sizes.

**Comment by hypno2000** [comment]
Thanks a lot. Will investigate.

**Comment by wojtekmach** [comment]
> Is the private organization and public package limit the same?

For now yes but we'll likely increase the limit for private packages in the future.
