### ISSUE TITLE
Possible deadlock/performance bug running `mix deps.get`

### ISSUE THREAD

**Issue by axelson** [hexpm/hex#672]
Reproduction repository at: https://github.com/axelson/dep_deadlock_umbrella (set to private so ask me if you want access, I've initially given it to @ericmj)

Note: you may need to checkout a version of db_connection at `/Users/jason/dev/forks/db_connection` (or change the path location)

It seems that with some combination of dependencies in an umbrella project it takes a really long time to resolve dependencies. So far I've waited 10 minutes for the "Resolving Hex dependencies..." step (ran for 700 seconds before killing).

Environment:
* Elixir 1.6.4 (compiled with OTP 19)
* Erlang/OTP 20
* hex 0.19.0
* Mac OS X 10.13.6

Note: I get the error even after removing the specification of `db_connection` completely (of course it will still be pulled in since it is a transitive dependency)

**Comment by shanesveller** [comment]
I witnessed something at least superficially similar just yesterday, on a project that wound up having conflicting versions of `comeonin` (4.x) and `argon2_elixir` (2.x) which are incompatible, but it took me some time and curiosity as a human being to notice and correct that. The `deps.get` command did not give me any feedback to the screen before my patience ran out, after several minutes.

Even if the tool can't rapidly reach a solution, perhaps just some periodic output that it's still trying (and some abstraction of progress, i.e. number of iterations or packages waiting to resolve) would have been a great user experience and would've pointed me to review my recently-changed dependencies more closely. I actually spent a few minutes trying to double-check network connectivity, DNS, looking in Slack for an outage, etc. first - because **this is the first time in a few years of Elixir that my dependency resolution didn't finish in seconds**! 😅

**Comment by akhilpai** [comment]
May have seen this as well when setting up a greenfield Phoenix project. Reducing the concurrency (i.e. https://github.com/hexpm/hex/issues/540#issuecomment-378636809 or https://github.com/hexpm/hex/issues/540#issuecomment-378817062) lets it complete.

**Comment by ericmj** [comment]
The current plan is to replace the resolver with an algorithm that can more aggressively trim the possible solution space when backtracking. When that is done we can revisit these issues to see if they have been resolved.
