### ISSUE TITLE
8MB tarball size limit

### ISSUE THREAD

**Issue by indocomsoft** [hexpm/hex#687]
I could not find the documentation regarding this limit anywhere -- I had to dig into the erlang source code to find out about this limit. Perhaps it would be good to document this somewhere.

Also, is there any possibility that this limit will be raised in the future?

Currently I am building a pure Elixir interface to the WordNet lexical/semantic database, similar to Ruby's `rwordnet`. I want to bundle the database directly with the package, but right now I need to compress the dataset in a `.tar.xz` so that it can fit under the 8MB tarball limit, while on rubygems, the limit is higher so `rwordnet` can just include the datasets uncompressed. I would really love to be able to remove the dependency on `tar` and `xz`.

**Comment by ericmj** [comment]
If it’s not documented then we should definitely have it documented. A PR to the mix hex.publish docs would be appreciated. There are currently no plans to increase the limit, we would need more examples of when it’s not enough before that. Data about the package size limits of other package managers would also be useful to help decide if we should increase the limit.

You shouldn’t have to compress before building the package because the 8MB limit is on the compressed data. So if it fits after you hade manuellt compressed then it should also fit uncompressed.

**Comment by JorisKok** [comment]
For my specific case, I am creating a dictionary app which is based on the Chinese public CEDict. The size is 9 mb +-, in a sqlite3 db. 

https://github.com/JorisKok/chinese_dictionary/tree/master/lib/dictionary

**Comment by indocomsoft** [comment]
I think my problem is that the dataset uncompressed is around 28 MB. With `gzip` algorithm used by default, the size of my dataset is around 8.5 MB. Only with `xz` algorithm (lzma) can I get to 5.9 MB. Alternatively, I can always split the data into multiple dummy packages.

With regards to other package managers, from what I can find:
Python pip: around 60 MB (https://github.com/pypa/packaging-problems/issues/86)
Ruby gems: around 500 MB (https://help.rubygems.org/discussions/questions/9633-maximum-allowed-size-of-a-fat-binary-gem)
Rust crate: 10 MB (https://doc.rust-lang.org/cargo/reference/publishing.html)
NodeJS npm: no limit but otherwise memory-bound since everything is done in-memory (https://github.com/npm/npm/issues/12750)

**Comment by supersimple** [comment]
![Screen Shot 2019-08-03 at 10 48 11 AM](https://user-images.githubusercontent.com/773380/62414695-38176280-b5dc-11e9-821b-b737e36f1859.png)


This documentation was added to hex.publish
Closing the issue. Thank you @indocomsoft for the info on other package managers. It's definitely something we should be considering.

**Comment by mickel8** [comment]
Hi @ericmj,
regarding use cases for increasing 8MB limit. 8MB can be too little when trying to write library which uses some third party code written in C (e.g. boringssl).  I wrote post on forum ([here](https://elixirforum.com/t/publishing-package-with-third-party-dependencies-written-in-c-like-boringssl/37529)) regarding difficulties when trying to publish such lib. We managed to find some workarounds but they are just workarounds. It would be really nice to be able to include such sources with lib in hex.

**Comment by ericmj** [comment]
Thanks for letting us know about your use case.

Is the source code of boringssl larger than 8MB when compressed? Is there no way to reduce it? What are the workarounds you are doing?

**Comment by wojtekmach** [comment]
Are you including the entire boringssl project or are you using only the required files and thus skipping things like tests, docs, etc?

**Comment by mickel8** [comment]
@ericmj regarding workarounds, I can precompile needed libs, release them somewhere (e.g. on github) and force user to download them before including my lib (or write mix task to download precompiled libs before compilation). 
Another way would be to write mix task which downloads needed libs using git modules. 
One more way is to force user to compile and install libs on his own. 

@wojtekmach I follow `quiche` while trying to include boringssl

**Comment by mickel8** [comment]
So compressed boringssl seems to be ~2.7MB and compressed lsquic ~3MB. Both libs include test files but don't include docs or fuzz files. Additionaly I include libev  in my repository and elixir files. Maybe I did something wrong because looking at these sizes I am not sure if I should exceed 8MB overall. Nevertheless  boringssl and lsquic will probably take sth between 4-6 MB so I don't have too much space for my own files.

**Comment by ericmj** [comment]
> Nevertheless boringssl and lsquic will probably take sth between 4-6 MB so I don't have too much space for my own files.

That should leave plenty of space for your own files unless they are also binary. Even large projects are usually less than 100kB.

**Comment by mickel8** [comment]
Oh I see.

I tried once again but including boringssl and lsquic is impossible at this moment. 
Here are files I try to include
```elixir
      files: [
          "lib",
          "mix.exs",
          "README*",
          "LICENSE*",
          ".formatter.exs",
          "bundlex.exs",
          "c_src/ex_quic/client.c",
          "c_src/ex_quic/client.h",
          "c_src/ex_quic/client.spec.exs",
          "c_src/ex_quic/lsquic_utils.c",
          "c_src/ex_quic/lsquic_utils.h",
          "c_src/ex_quic/libev/*.[ch]",
          "third_party/boringssl/**/*.[chS]",
          "third_party/boringssl/**/*.cc",
          "third_party/boringssl/**/CMakeLists.txt",
          "third_party/boringssl/**/sources.cmake",
          "third_party/boringssl/LICENSE",
          "third_party/lsquic/**/*.[ch]",
          "third_party/lsquic/**/CMakeLists.txt",
          "third_party/lsquic/**/*.pl",
          "third_party/lsquic/**/*.sh",
          "third_party/lsquic/LICENSE.chrome",
          "third_party/lsquic/LICENSE"
        ]
```
Excluding libev files or lsquic files doesn't help so even when trying to include only boringssl I cannot do that. Excluding `.cc` files from boringssl helps. I am not sure why. `*cc` files have more than 30MB so after compression they should be okay. We don't have to solve this. Just mentioning that this may be a case for increasing the limit (or I am still doing something wrong).

**Comment by ericmj** [comment]
Can you share the project where you hit the tarball size limit?

**Comment by mickel8** [comment]
Yeah, sure. Thanks a lot for the help. My project is availabe here: https://github.com/mickel8/ex_quic/tree/hex-release 
Branch: `hex-release`

**Comment by ericmj** [comment]
The reason we have the limit is to prevent bad practices where users include unnecessary files in their packages and to prevent bad experiences for users with not as good internet connections.

You have a valid use case for a large package so the limit does not help in your case of course. It seems like you can fit your package within the limit – when running `mix hex.build` I get a 5.3MB tarball. An  option if you get close to limit is to split boringssl and lsquic into their own packages.

In the future we may also increase the limit for packages on a case by case basis for those that need it. But we are keeping the general limit because it is correct for >99% of packages.

**Comment by mickel8** [comment]
Damn, you're right :man_facepalming: 
Releasing clean repo (I mean with submodules) gives 5.3MB (as you said). It seems that compiling boringssl generates some more files and trying to relase after building it locally gives 8.3MB. Thanks a lot!

**Comment by ericmj** [comment]
> Releasing clean repo (I mean with submodules) gives 5.3MB (as you said). It seems that compiling boringssl generates some more files and trying to relase after building it locally gives 8.3MB. Thanks a lot!

Try to tweak your `package: [files: ...]` config to exclude them. You can also use `:exclude_patterns` to further exclude certain files.
