### ISSUE TITLE
Allow Custom CA's

### ISSUE THREAD

**Issue by djthread** [hexpm/hex#690]
I found #146 which speaks to exactly the issue. I'm opening this one because @ericmj asked me to :)

My current workaround is to set the environment variable `HEX_UNSAFE_HTTPS` as `1`, but it would be nice to have the ability to inject my company's CA somehow as trusted.

Thank you!!

**Comment by Exadra37** [comment]
I am all in favour of adding support for custom self signed certicates, as I pointed out at https://github.com/hexpm/hex/issues/137#issuecomment-493025140:

> Turning of HTTPS should be strongly discouraged, and instead provide the proper mechanisms to make any tool work in a corporate environment where Firewalls and Proxies are very common, otherwise we are just defeating the proposes of using this Firewalls and Proxies, that are to secure the environment we are in.

Another very important factor to bear in mind is that when a company that needs certifications in order to provide services to other companies, may not be able to software that do not allow to run safely behind a Firewall or Proxy, because that will violate the certification or making impossible to obtain one.

### Some Context: Firewall is not the same as using a proxy

I am alerting for this in order to avoid suggestions of configuring the proxy environment variables.

So a  Firewall does the https termination, inspects the content in the request, with an anti-virus software, and if no virus is found it will re-encrypt the request with a self signed certificate and sends the request to the intended destination in our internal network, aka our computer, that have the Firewall self signed certificate installed in the trusted store of the operating system and in the trusted store of each software we use, that does not use the operating system trusted store.

**Comment by wojtekmach** [comment]
Closing in favour of #727.
