### ISSUE TITLE
Strange behaviour of "~>" version with the :amqp package on hex >= 0.19.0

### ISSUE THREAD

**Issue by rbino** [hexpm/hex#704]
## Steps to reproduce
- `mix new test`
- Add `{:amqp, "~> 1.0"}` dep
- `mix deps.get`

## Expected behaviour
The latest version (`1.2.1` currently) is fetched.

## Actual behaviour
Version `1.0.0` is fetched.

## Additional info
If `"~> 1.2"` is specified, then version 1.2.1 is installed, but if it's reverted back to `"~> 1.0"` and `mix deps.update --all` is run, the package gets downgraded to 1.0.0.

This seems to be introduced with version 0.19.0 (and still present in 0.20.1), downgrading to 0.18.2 seems to fix the problem.

**Comment by rbino** [comment]
Using `git bisect` I've determined the first commit that introduced the problem is 93720ddfb0bfe2074e6369708ebd0ff355ffe749.

**Comment by ericmj** [comment]
This is a known issue the hex version resolver have with the rabbitmq family of packages. The resolver assumes packages use semver but `amqp_client` and children do not which causes the resolver to have troubles selecting the version you expect.

We tried to work around this problem by considering every possible solution to the resolution problem and selecting the best solution. Unfortunately we had to revert this in 93720dd because the resolver became too slow (version resolution is NP-complete so some optimizations that skips solutions and assumes semver is necessary).

We have reported the issue to the rabbitmq team. You can work around the issue by setting a strict version requirement such as `{:amqp, "1.2.1"}`.

**Comment by rbino** [comment]
Thanks for the explanation.

I see that https://github.com/hexpm/hex/commit/93720ddfb0bfe2074e6369708ebd0ff355ffe749 effectively reverts two commits at once: c47e73aa35f2f3d1cb82a786ddcc8432398e96c2 (which introduces the backtracking euristic) and 1ec25e0b1b19dda5ac217acdcfec382f7e316ef5 (which just backtracks children before parents).

If I reapply just what was done in 1ec25e0b1b19dda5ac217acdcfec382f7e316ef5, the bug does not appear anymore, but at the same time there's not a big performance penalty. I tested with the [explode repo](https://github.com/dch/explode/) that was linked in https://github.com/elixir-lang/elixir/issues/8291 and the difference is negligible (~9.4 seconds without, ~9.7 seconds with).

I don't know if there are other implications I'm not aware of, but it seems that 1ec25e0b1b19dda5ac217acdcfec382f7e316ef5 can be restored and, at least, solve this specific instance of the problem.

**Comment by rbino** [comment]
Nevermind - the fix works for the small failing example I posted above but it doesn't when in the context of a larger project.

I'll just use explicit versions for `amqp` related stuff for now, thanks.
