### ISSUE TITLE
Proposal to add `mix hex.bump`

### ISSUE THREAD

**Issue by edisonywh** [hexpm/hex#715]
I'd like to propose a new Mix task, `mix hex.bump` to simplify version bumping a library.

The ideal workflow for me would go something like this:
```
# Code your changes
# ...
> mix hex.bump minor # usage: [major | minor | patch]
#=> Bump `library` from version `0.1.5` to `0.2.0`
> mix hex.publish
```

Some additional things that I think can be useful down the road:
- add a `--dry-run` switch that simulates running (shows you what version it'll bump to), but without actually changing `mix.exs`/creating a tag.
- add a `--changelog` switch to generate a `CHANGELOG.md`, which is just a file concatenating the commit messages since the last version tag. This could also nudge people to write cleaner commit messages, because you can get changelog for free.

This can lower down the context switch that a developer has to do when he/she wants to publish a new version of package (open up editor, go to line X, change a file, git add & commit, tag release, hex.publish). It's a problem that I faced, and I often forget to tag a release.

Let me know what you think, and looking forward to your replies!

I'm also happy to help out on this as well!

## References:

I got this idea from the Ruby community, namely [`gem-release`](https://github.com/svenfuchs/gem-release)

While searching around I also found someone has published an Elixir package that does this too, called [`mix-bump`](https://github.com/oo6/mix-bump), the package looks great, but I think something like this can be more useful in core Hex.

**Comment by whatyouhide** [comment]
@edisonywh we have a big problem with this: our `mix.exs` file is completely dynamic as it's just Elixir code. For example, sometimes I use `version: "2.0.1"` in the `project/0` function, but sometimes I extract the version in `@version "2.0.1"` at the top of the file and then have `version: @version` in `project/0`. This means that there is no way that we can correctly update the version programmatically in `mix.exs` since we really don't know where it is. FWIW, if I have `@version ...` this already breaks the `mix-bump` package. If you want more context, there are many discussions in the [Elixir core mailing list](https://groups.google.com/group/elixir-lang-core) that propose something like `mix deps.add` (to add a dependency), which is conceptually the exact same thing.

As for the changelog, right now I don't think Hex does any Git operations like reading commits or issuing any "write" Git command such as tagging, right Hex team? Plus we have the same problem that not everybody uses `CHANGELOG.md` in the exact same way.

All of this to say that personally I don't think all of this is worth for just bumping a version and doing some pre-release work. :)

**Comment by supersimple** [comment]
> As for the changelog, right now I don't think Hex does any Git operations like reading commits or issuing any "write" Git command such as tagging, right Hex team?

Yes, publishing has no requirements on git. (technically hex.diff does require git locally, but that is the only time we rely on git)

I have definitely heard similar requests to this before, so I think there is some merit to the idea.
Things to think about:
1. the git_bump package has relatively few downloads, so maybe there arent as many people demanding this as it seems.
2. We generally think of releases as happening on the cadence of once/month or sometimes less. Automating actions for this frequency might just be a luxury.
3. I like the idea you mentioned of generating a changelog, in general we have been trying to make the difference in releases more obvious to users. However, there is no guarantee that what exists on github is the code you are downloading from the hex registry.
4. It occurs to me this type of utility would be useful to all mix applications, not just hex releases. Perhaps there is a good solution that could be added into Mix itself to do this. @whatyouhide has this been discussed?

Edison - thank you for your contribution. Whether this is implemented or not shouldnt discourage you from continuing to contribute ideas/code to the project. We appreciate your support 🍻

**Comment by ericmj** [comment]
I don't think we will extend Hex with git specific features and there's less chance we will extend Elixir with such features. We have discussed adding changelogs to Hex packages, but I don't think there is way to auto-generate them.

If there already is a `mix_bump` package that does some of this then I think that is what should be used and we should focus on extending that package with new features.

**Comment by edisonywh** [comment]
Cool, thanks for all the comments guys! You guys raised some good points, and so I rest my case!

Thanks for everything that you guys have done for the Elixir community :)
