### ISSUE TITLE
Add epub version to documentation

### ISSUE THREAD

**Issue by supersimple** [hexpm/hex#732]
generated from: https://github.com/hexpm/hex/issues/731

current thoughts:

- Generate epub version along side html version and include it in the tarball.
- Add flag for hex.docs tasks for epub (`mix hex.docs offline --epub` would open the epub file instead of default html page.)
- ...

**Comment by ericmj** [comment]
I am outlining some of the steps and different options we have for implementing this:

* When generating docs during `mix hex.publish` we need to also call `mix docs --formatter epub` since ex_doc only runs the HTML generator by default.
* We can either include the epub in a known location in the current docs tarball or store it separately. If separately we need a new API endpoint for uploading it and a new repository endpoint to download it. If it is included we need to store it a known location for example `tarball_root/docs.epub`, all docs will not include this file so we always need to be aware it can be missing.
* `mix hex.docs fetch` should probably fetch both HTML and epub docs, if the epub is stored in the docs tarball we get this for free.

**Comment by josevalim** [comment]
It is really easy to ask ExDoc to generate both, so I would push the burden to the ExDoc config:

https://github.com/phoenixframework/phoenix/blob/cfb83d9eff1373d44a8d811e77b22beac0f9a42a/mix.exs#L107

If you want a mechanism to show the epub, simple do a Path.wildcard(*.epub) at the root of the dos folder and open up what shows up.

This would be the simplest approach IMO. :)

**Comment by supersimple** [comment]
- adding epub to the docs formatters as @josevalim suggested works well, and is probably the easiest.
- i agree `mix hex.docs fetch` should get all doc formats.
- the default file seems to be :application_name.epub. I think we could use that as the "known" location.
- the big work for hex seems to me to be supporting the `--epub` flag on offline
