### ISSUE TITLE
`mix deps.get` fails to fetch certain versions of libraries

### ISSUE THREAD

**Issue by riverrun** [hexpm/hex#756]
This relates to two issues that have been reported in libraries that I maintain - [pbkdf2_elixir issue](https://github.com/riverrun/pbkdf2_elixir/issues/6) and [bcrypt_elixir issue](https://github.com/riverrun/bcrypt_elixir/issues/26).

In both cases, `mix deps.get` fails to fetch the newest version of the package, version 1 for pbkdf2_elixir and version 2 for bcrypt_elixir.

I have advised the users to update hex, but that does not seem to work.

Are there any changes I can make to the setup of the packages that might help solve this?

Or do you have any other suggestions for these users?

**Comment by ericmj** [comment]
The pbkdf2 issue is probably happening because it's a larger package than most other so if users have bad internet connections it's more likely they run into issues with pbkdf2. The package is 1500kb and the HTTP timeout is set to 120s so it requires a sustained 12,5 kb/s download speed. If this is not enough the timeout needs to be increased. We are planning to switch HTTP clients which allow us to do "timeout since last byte" instead of "timeout for entire request", this should help users with slow connections but we cannot improve it with the HTTP client we use now.

It is possible there is another issue but there's not enough information from the issue you linked.

The second issue I cannot reproduce either so I can't exactly tell what is going on. We have had similar issues where the resolver is slow for the comeonin family of packages, they were caused by comeonin flipping the dependency tree in the v5 release. Instead of comeonin depending on all packages, the package started depending on comeonin insead. Because of this most assumptions the resolver makes when backtracking conflicts are incorrect and it will take a very long for it find the correct solution or give up because it's not solvable.

Version resolution is an NP-hard problem so there will always be scenarios where this can happen. As I have mentioned in this issue https://github.com/hexpm/hex/issues/752 we are working on improving the resolver but that's a long term project.

Unfortunately we cannot help your users directly without more information or preferably a way to reproduce the issues. If they can provide more information please ask them to open issues here.

**Comment by riverrun** [comment]
Thanks for the detailed reply. I will pass the information on to the affected users.

**Comment by riverrun** [comment]
About comeonin flipping dependencies in v5, if you feel that that is a serious problem, please open an issue at the comeonin repo, and we can discuss how to solve it (possibly moving that functionaliy to a different library, for example).

**Comment by ericmj** [comment]
The comeonin change has already happened and exists in the package index so it's too late to change. But the fact that the resolver gets stuck on comeonin is not the package's fault, it's definitely a hex bug, so we should rather try to fix it in hex rather instead of comeonin trying to workaround the issue.
