### ISSUE TITLE
Tool for finding what pulls in a dependency

### ISSUE THREAD

**Issue by davydog187** [hexpm/hex#769]
# The Problem
I ran into an issue where the version of `hackney` installed in my project was breaking a direct dependency of mine. Since `hackney` was a transitive dependency, I first needed to find which direct dependencies were pulling in `hackney`, so that I could update them.  

# Potential Solutions

## Add parent dependencies to `mix hex.info`
List the dependencies that pull in this transitive dependency.

`mix hex.info hackney`

```
$ mix hex.info hackney
simple HTTP client

Config: {:hackney, "~> 1.15"}
Releases: 1.15.2, 1.15.1, 1.15.0, 1.14.3, 1.14.2, 1.14.0, 1.13.0, 1.12.1, ...
Depended by: :ex_coveralls, :httpoison

Licenses: Apache 2.0
Links:
  Github: https://github.com/benoitc/hackney
```

## Add a feature to `mix deps.tree` to show the reverse tree of dependencies that pull in that dependency

`mix deps.reverse_tree` - Show the tree of packages that pull in that package. e.g. `mix deps.reverse_tree hackney` would show `HTTPoison`, etc

`mix deps.tree --include` - Only show the tree that includes that dependency

### Notes
I've discussed this with a few new friends at Code BEAM SF, and I would love to hear feedback from others on what would be useful to others in the community. Then I would like to implement this feature :)

**Comment by supersimple** [comment]
`mix deps.tree --include` - it is possible there are multiple branches that contain the same dep (i assume you want to show all of them in this case.) "include" does seem to be the opposite of "exclude", and this feature seems to describe a behavior that is opposite. so, I think it makes sense.

instead of adding a new task `reverse_tree`, what do you think of a `reverse` flag that requires one dependency name? eg. `mix deps.tree hackney --reverse`. Since the functionality is very similar to what is (and will be) in mix deps.tree, having the flag there makes sense in my brain.

WDYT?

**Comment by ericmj** [comment]
Should we move this issue to elixir-lang/elixir since `mix deps.tree` comes from stdlib?

/cc @josevalim

**Comment by josevalim** [comment]
I think it belongs to Elixir indeed. We likely wouldn't track it in our issues tracker but a PR is definitely welcome!

**Comment by davydog187** [comment]
Sounds like I have a hacktoberfest PR to cook up
