### ISSUE TITLE
Allow publishing docs for packages with overrides

### ISSUE THREAD

**Issue by hauleth** [hexpm/hex#807]
In my job I have implemented alternative Hex repo for our internal use (mostly docs) and we have encountered issue. Namely we use `override: true` a lot in the end applications and it causes problems when trying to publish docs for such package, as `mix hex.build` cannot build such. As we are using it only for hosting documentation then I do not care about dependencies at all. It would be handy to skip that checks when running `mix hex.publish docs` (potentially behind a flag like `--allow-overrides`).

**Comment by ericmj** [comment]
I assume you are using a custom Hex server that allows you to publish any tarball without an associated package since hex.pm does not allow that?

If that's correct you are not using any of the package features and a custom task that calls `:erl_tar` and makes a POST request to your server should work.

**Comment by hauleth** [comment]
> I assume you are using a custom Hex server that allows you to publish any tarball without an associated package

Yes. Additionally I hope that I will be able to open it soon.

> If that's correct you are not using any of the package features and a custom task that calls :erl_tar and makes a POST request to your server should work.

Well, it doesn't as `mix hex.publish` will **always** call `mix hex.build` which do not allow such packages. So even without any HTTP request it will fail.
