### ISSUE TITLE
Pushing unpublished version to hexdocs has poorly formated error

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex#84]
```
$ mix hex.docs
Docs successfully generated.
View them at doc/index.html.
[#########################] 100%Pushing docs for sbroker v0.3.0 failed
Entity not found (404)
%{"message" => "Not Found", "status" => 404}
```
Source: hexpm/hex_web#92

**Comment by jcspencer** [comment]
This 404 is returned [here](https://github.com/hexpm/hex_web/blob/master/lib/hex_web/api/router.ex#L53) in the API router. Should we improve the server side response, or simply throw a different client side error?

**Comment by ericmj** [comment]
The server response is fine. We don't throw an error in the client, we just print an error message. It should be printed as:

```
$ mix hex.docs
Docs successfully generated.
View them at doc/index.html.
[#########################] 100%
Pushing docs for sbroker v0.3.0 failed
Entity not found (404)
```

**Comment by jcspencer** [comment]
The map (`%{"message" => "Not Found", "status" => 404}`) is being printed from [here](https://github.com/hexpm/hex/blob/master/lib/mix/tasks/hex/docs.ex#L80); the fix is as simple as removing the line.

The line break issue is fixed for the success case, but not the failure case. It's fixed by calling `Mix.shell.info("")` [here](https://github.com/hexpm/hex/blob/master/lib/mix/tasks/hex/docs.ex#L78)
