### ISSUE TITLE
mix deps.get failed with Killed error

### ISSUE THREAD

**Issue by sarsonj** [hexpm/hex#857]
Hi,

we are using same package for about a year. We build app in Docker container (elixir:1.11, but I tried also other versions), using docker version of elixir. It worked perfectly, until today. Because mix deps.get don't have verbose mode, I am not sure, where the problem is.

I have mix.exs with those dependencies:

```
  defp deps do
    [
      {:ejabberd,
       git: "https://github.com/tappytaps/ejabberd.git",
       ref: "213f2b248a067a35769de0f73c782edcc3ad2c7d"},
      {:pigeon, "~> 1.5"},
      {:kadabra, "~> 0.4.5"},
      {:exprotobuf, "~> 1.2"},
      {:jason, "~> 1.2"},
      {:distillery, "~> 2.1"},
      {:xmpp, "~> 1.0"},
      {:logger_lager_backend, "~> 0.2.0"}
    ]
  end
```

When I run `mix deps.get` its "Resolving Hex dependencies..." for few seconds and then failed with `Killed` error. Maybe stack overflow or something like this?

When I try to remove `pigeon` package from dependency, it works. When i add it back then and run `mix deps.get` again, it works as well and it also installs `pigeon` package. So that it looks like that there is problem with dependency detection, maybe circular dependency?

Is there any way to enable verbose logging to mix deps.get to see, what is actually happening?

Thanks!

**Comment by ericmj** [comment]
Please include your `mix.lock` file in the state it is when `mix deps.get` fails with `Killed`.

I am guessing it is running out of memory due to the large amounts of backtracking it needs to do find a valid dependency resolution. How much memory are you giving to docker?

**Comment by sarsonj** [comment]
Hi,

I am starting with just mix.exs. There is no mix.lock, before or after running mix deps.get.

**Comment by Eiji7** [comment]
I can reproduce it also outside `Docker`. Just generated project `mix new example` and replaced `deps` function as in issue. Here is a graph of memory usage:

![obraz](https://user-images.githubusercontent.com/10956022/105911868-eca41000-602a-11eb-9a27-1533d935f080.png)

As you can see it took not only whole memory (16GB), but also whole swap (also 16GiB) and I was in need to kill `beam.smp` as it wasn't going to stop on that.

**Comment by kamilkowalski** [comment]
I just bumped into this problem in my project - it's possible to reproduce even with one dependency (`ejabberd` pinned to `19.9.1`): https://replit.com/@kamilkowalski3/DepsFetch#mix.exs It will start resolving deps only to be killed (probably due to excessive memory usage).

I'd like to help but I can't seem to understand how `Hex.Resolver` works - I tracked the issue to that module. It continues to walk into the `run/4` function and never finishes processing the `pending` list.

**Comment by benonymus** [comment]
I am facing this as well, out of nowhere.
Is there any workaround?

**Comment by pmarreck** [comment]
I'm having the same problem. `mix deps.update --all` consumes all available memory on any given device or VM (I tried 3) and then either hangs your machine or gets OOMkilled. I was watching `top` while it was happening.

A link to my most recently committed mix.exs and mix.lock are here (from about 3 months ago, that's why I was updating...):
https://github.com/pmarreck/mpnetwork/blob/yolo/mix.exs
https://github.com/pmarreck/mpnetwork/blob/yolo/mix.lock

@ericmj , let me know if you need any additional assistance running it down, and thanks in advance

**Comment by ericmj** [comment]
We may have possible fix for this issue in the main branch. Please try it and report back if the issue is fixed or you are still having issues.

Install main: `mix archive.install github hexpm/hex`.
Install stable: `mix local.hex`.

**Comment by pmarreck** [comment]
So I switched to main and tried again.
Whatever you did not only fixed it, but it blew through 23 updates (yeah I counted) in like < 3 seconds! You're the MAN, @ericmj ! And best of all, all my tests still pass! Thanks!!

**Comment by ericmj** [comment]
Glad to hear it solved the issue.

It was @NickNeck who solved it, by finding a better heuristic to decide on which package to backtrack on.
