### ISSUE TITLE
Add a `:replace` option

### ISSUE THREAD

**Issue by ryanwinchester** [hexpm/hex#871]
## Scenario:

Dependency `A` is no longer maintained. Dependency `B` is a fork that is a backwards-compatible replacement for `A`.

I have a project that has dependencies that depend on the unmaintained `A`, and I myself want to use `B`, or have dependencies that use `B`.

If I could do in my project:

```elixir
{:package_b, "~> v1.6", replaces: :package_a}
```

Then hex could know to just completely ignore the `:package_a` dependency, since it is replaced by `:package_b`.

This should probably also only be an allowable option in the current project and not in dependencies.

## Precedence

The PHP package manager has a similar option:

* https://getcomposer.org/doc/04-schema.md#replace

**Comment by ericmj** [comment]
This would need to be implemented in Elixir, but I do not think we would like to add this because you would only need this if you do not follow the namespacing conventions. `package_b` shouldn't use the namespace `PackageA` so if you want to replace modules in `package_a` you should also name the application that replaces it `package_a`.

I am going to close this issue because it's not actionable in Hex but feel free to continue the discussion.
