### ISSUE TITLE
Cache returns outdated files

### ISSUE THREAD

**Issue by thojanssens** [hexpm/hex#890]
I depend on a library like so:
```elixir
{:some_repo, git: "git://github.com/author/some_repo.git",
        branch: "master",
        override: true}
```
The problem is that I won't get the latest version of the code. Old code is returned from the cache.
Is there any way to clear the cache?

**Comment by ericmj** [comment]
Can you show what commands you are running? If you wish to update a dependency you need to run `mix deps.update`. There is no cache for git dependencies.

Hex is only used for Hex dependencies, git dependencies are handled by Elixir itself. I am closing this issue since it's not relevant to this repo but you can still comment with follow ups.
