### ISSUE TITLE
Hang and not helpful warning on mix deps.update --all

### ISSUE THREAD

**Issue by lukaszsamson** [hexpm/hex#902]
Originally reported in https://github.com/elixir-lang/elixir/issues/11208

The new warning from hex master is not helpful - it would be more useful if it could print the deps that are causing the the computational explosion that hex is unable to handle. Otherwise what is left is going through all of the deps and tightening the requirements.

**Comment by ericmj** [comment]
This is not easy to determine so it's better to focus the development time on fixing the resolver so the warning is not needed.

I'm not sure what the combinatorial problem is? You can either update individual dependencies with `mix deps.update APP` or constarin the version on individual deps until the problem is solved.

**Comment by ericmj** [comment]
The new resolver is still at least a few months away since it's a rewrite from scratch and it will need to be run in parallel with the existing one to test against regression errors.

If you or someone else have ideas on how we can improve the existing resolver, either by improving the warning or preventing it in the first place, we would be happy for any PRs or to discuss it.
